// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfjowdvrqjxcafiofwlk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmam93ZHZycWp4Y2FmaW9md2xrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NTg3ODQsImV4cCI6MjA3MTEzNDc4NH0.gYSqqwPoCf34I6Hyx3CGY4fFipczRKq8KYpC-tine7Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});